import Sidebar from "@/components/global/Sidebar";
import SidebarProvider from "@/contexts/SidebarProvider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "LizBoutique - Inventory",
  description: "Generated by bb Kielo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="w-full min-h-screen relative">
      <SidebarProvider>
        <Sidebar />
        {children}
      </SidebarProvider>
    </div>
  );
}
